{{- if and .Values.ingress.enabled (ne .Values.ingress.tls.mode "manual")}}
{{- $tlsSuffix := include "k8laude.tlsSuffix" . -}}
{{- if eq .Values.ingress.tls.mode "selfsigned"}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{.Release.Name}}-selfsigned
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/instance: {{.Release.Name}}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Release.Name}}-tls
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/instance: {{.Release.Name}}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
spec:
  secretName: {{.Release.Name}}-tls
  issuerRef:
    name: {{.Release.Name}}-selfsigned
    kind: Issuer
  dnsNames:
    - {{.Values.ingress.host}}
  duration: 8760h
  renewBefore: 720h
{{- end}}
{{- if eq .Values.ingress.tls.mode "auto"}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Release.Name}}-tls{{$tlsSuffix}}
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/instance: {{.Release.Name}}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
spec:
  secretName: {{.Release.Name}}-tls{{$tlsSuffix}}
  issuerRef:
    name: {{.Release.Name}}-letsencrypt{{$tlsSuffix}}
    kind: Issuer
  dnsNames:
    - {{.Values.ingress.host}}
    - "*.{{.Values.ingress.host}}"
{{- end}}
{{- end}}
