apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-preflight
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    troubleshoot.sh/kind: preflight
type: Opaque
stringData:
  preflight.yaml: |
{{ include "k8laude.preflight" . | indent 4 }}
