apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-supportbundle
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    troubleshoot.sh/kind: support-bundle
type: Opaque
stringData:
  support-bundle-spec: |
{{ include "k8laude.supportbundle" . | indent 4 }}
