apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cloudtty
  labels:
    app.kubernetes.io/name: cloudtty
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- if .Values.rbac.clusterAdmin }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-cloudtty-admin
  labels:
    app.kubernetes.io/name: cloudtty
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-cloudtty
    namespace: {{ .Release.Namespace }}
{{- end }}
