apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: k8laude
spec:
  chart:
    name: k8laude
    chartVersion: ""

  helmUpgradeFlags:
    - --timeout
    - 5m
    - --wait

  values:
    replicated:
      enabled: true
      nameOverride: k8laude-sdk
    image:
      repository: '{{repl HasLocalRegistry | ternary LocalRegistryHost "ghcr.io" }}/{{repl HasLocalRegistry | ternary LocalRegistryNamespace "scottrigby" }}/k8laude'
    imagePullSecrets:
      - name: '{{repl ImagePullSecretName }}'
    fluentbit:
      image:
        repository: '{{repl HasLocalRegistry | ternary LocalRegistryHost "docker.io" }}/{{repl HasLocalRegistry | ternary LocalRegistryNamespace "fluent" }}/fluent-bit'
    ingress:
      enabled: false
    cert-manager:
      enabled: false
    traefik:
      enabled: false
    claude:
      oauthToken: '{{repl ConfigOption "oauth_token" }}'
      apiKey: '{{repl ConfigOption "api_key" }}'
      debug:
        enabled: '{{repl ConfigOptionEquals "debug_logging_enabled" "1" }}'
    postgresql:
      enabled: '{{repl and (ConfigOptionEquals "debug_logging_enabled" "1") (ConfigOptionEquals "debug_log_storage" "builtin") }}'
      auth:
        password: '{{repl ConfigOption "embedded_db_password" }}'
    externalDatabase:
      host: '{{repl ConfigOption "external_db_host" }}'
      port: '{{repl ConfigOption "external_db_port" }}'
      username: '{{repl ConfigOption "external_db_username" }}'
      password: '{{repl ConfigOption "external_db_password" }}'
      database: '{{repl ConfigOption "external_db_name" }}'
    cloudtty:
      enabled: '{{repl ConfigOptionEquals "cloudtty_enabled" "1" }}'
      auth:
        password: '{{repl ConfigOption "cloudtty_auth_password" }}'
      image:
        repository: '{{repl HasLocalRegistry | ternary LocalRegistryHost "ghcr.io" }}/{{repl HasLocalRegistry | ternary LocalRegistryNamespace "scottrigby" }}/k8laude-cloudtty'
    code-server:
      enabled: '{{repl ConfigOptionEquals "code_server_enabled" "1" }}'
      password: '{{repl ConfigOption "code_server_password" }}'
      image:
        repository: '{{repl HasLocalRegistry | ternary LocalRegistryHost "ghcr.io" }}/{{repl HasLocalRegistry | ternary LocalRegistryNamespace "scottrigby" }}/k8laude-code-server'

  namespace: '{{repl Namespace }}'
  builder:
    replicated:
      enabled: true
